---
- hosts: localhost

  vars:
    user: mortal
    password: r3dh4t1!

  tasks:
#    - include_vars: credential.yml
    - name: get authtoken
      uri:
        url: https://localhost/api/v1/authtoken/
        method: POST
        body: '{ "username": "{{ user }}", "password": "{{ password }}" }'
        body_format: json
        validate_certs: no
      register: authtoken
    - name: display authtoken
      debug:
        vars: authtoken

    - name: get projects
      uri:
        url: https://localhost/api/v1/projects/
        method: GET
        return_content: yes
        headers:
          Authorization: "Token "
        validate_certs: no
      register: projects

    - debug:
         vars: projects
