---
- name: Upgrade Non Kernel Packages
  hosts: all
  # should only be RPM style machines
  become: true

  tasks:
  - name: upgrade all but kernel packages
    yum:
      name: '*'
      state: latest
      exclude: kernel*
